spring:
  application:
    name: USER-SERVICE
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 'ygz123'
    url: jdbc:mysql://localhost:3307/vechiletracking?createDatabaseIfNotExist=true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
eureka:
  client:
    fetch-registery: true
    register-with-eureka: true  
    service-url:
      default-zone: http://localhost:8761/eureka
    instance:
      instance-id: ${spring.application.name}:${random.value}
      prefer-ip-address: true 
server: 
  port: 0